project_id = "psiscvlfkpkytfdcpdma"

[functions.retell-webhook]
verify_jwt = false

[functions.create-call]
verify_jwt = false

[functions.ghl-webhook]
verify_jwt = false

[functions.create-tavus-conversation]
verify_jwt = false

[functions.calcom-booking]
verify_jwt = false

[functions.tavus-tool-handler]
verify_jwt = false
