import {
  pgTable,
  text,
  uuid,
  timestamp,
  integer,
  boolean,
  index,
  varchar,
} from "drizzle-orm/pg-core";

// ── Booking Schema (PostgreSQL) ──
// Extends the existing Drizzle schema with booking session
// and PURL tracking tables. Uses the same Neon PostgreSQL backend.

/**
 * booking_sessions — Tracks the full lifecycle of a booking
 * from V·FACE conversation initiation through PURL generation
 * and eventual booking completion.
 */
export const bookingSessions = pgTable(
  "booking_sessions",
  {
    id: uuid("id").primaryKey(), // Generated by application via crypto.randomUUID()
    conversationId: text("conversation_id").notNull(),
    memberName: text("member_name").notNull(),
    memberId: text("member_id"), // Loyalty / membership number
    travelType: text("travel_type").notNull(), // cruise, hotel, flight, etc.
    destination: text("destination"),
    departureWindow: text("departure_window"),
    travelers: integer("travelers").notNull().default(2),
    budgetRange: text("budget_range"),
    specialRequests: text("special_requests"),

    // Search state
    lastSearchId: text("last_search_id"),
    lastSearchResults: text("last_search_results"), // JSON string of result summaries

    // Selection state
    selectedPackageId: text("selected_package_id"),
    selectedPackageSummary: text("selected_package_summary"),

    // Status lifecycle
    status: varchar("status", { length: 32 }).notNull().default("initiated"),
    // Valid: initiated | searching | results_presented | package_selected |
    //        purl_generated | purl_clicked | booking_completed | expired | cancelled

    // Metadata
    correlationId: text("correlation_id").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    index("booking_sessions_conversation_idx").on(t.conversationId),
    index("booking_sessions_status_idx").on(t.status),
    index("booking_sessions_member_idx").on(t.memberId),
  ]
);

/**
 * purl_records — Tracks every generated PURL for analytics,
 * expiry management, and click tracking.
 */
export const purlRecords = pgTable(
  "purl_records",
  {
    id: uuid("id").primaryKey(), // Generated by application
    bookingSessionId: uuid("booking_session_id")
      .notNull()
      .references(() => bookingSessions.id),
    purl: text("purl").notNull(),
    deliveryMethod: varchar("delivery_method", { length: 16 }).notNull(), // sms, email, display, all
    memberEmail: text("member_email"),
    memberPhone: text("member_phone"),

    // Tracking
    clickedAt: timestamp("clicked_at", { withTimezone: true }),
    clickCount: integer("click_count").notNull().default(0),
    userAgent: text("user_agent"), // Captured on first click
    ipAddress: varchar("ip_address", { length: 64 }), // Captured on first click (hashed)

    // Expiry
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    isExpired: boolean("is_expired").notNull().default(false),

    // Metadata
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    index("purl_records_session_idx").on(t.bookingSessionId),
    index("purl_records_expires_idx").on(t.expiresAt),
  ]
);

// ── Types ──
export type BookingSession = typeof bookingSessions.$inferSelect;
export type NewBookingSession = typeof bookingSessions.$inferInsert;
export type PurlRecord = typeof purlRecords.$inferSelect;
export type NewPurlRecord = typeof purlRecords.$inferInsert;
